sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.6"  # these are just to make travis's UI a bit prettier
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34-twisted
    - python: "3.4"
      env: TOXENV=py34-aiohttp
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35-twisted
    - python: "3.5"
      env: TOXENV=py35-aiohttp
    - python: "3.5"
      env: TOXENV=py35
    - python: "pypy"
      env: TOXENV=pypy

    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=manifest
    - python: "2.7"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=readme


install:
  - pip install tox


script:
  - tox --hashseed 0


before_install:
  - pip install codecov


after_success:
  - codecov


notifications:
  email: false
